### ISSUE TITLE
emojis in pug displayed as boxes

### ISSUE THREAD

**Issue by salini-reddim** [zekrs/aws-nodejs-ts-pdf#3]
p &#128176;
Hi I have included emojis in the pug, but in the pdf they are showing as boxes. How can I fix this

**Comment by zekrs** [comment]
Hi. Are you able to share any code snippet, how you add emojis on page?
I tried to add &#128522; with this code `&#128522;` and it printed nicely in pdf.  Like this: 
`p Some test text with emoji &#128522;`

**Comment by zekrs** [comment]
@salini-reddim I am making some modifications to another project of same type and I saw this:
https://www.npmjs.com/package/chrome-aws-lambda?activeTab=readme#fonts

**Comment by salini-reddim** [comment]
Thank you for the reply. It worked when I included the fonts.
